#!/usr/bin/env python
"""
Autogenerate an Alembic migration from current models and upgrade to head.
Usage:
  python scripts/autogen_and_upgrade.py "message"
"""
import sys
from dotenv import load_dotenv
from alembic.config import Config
from alembic import command

def main() -> int:
    load_dotenv()
    msg = sys.argv[1] if len(sys.argv) > 1 else "autogen"
    cfg = Config("alembic.ini")
    command.revision(cfg, autogenerate=True, message=msg)
    command.upgrade(cfg, "head")
    print("Autogenerated migration and upgraded to head.")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
