#!/usr/bin/env python
"""
Generate dummy courses and lessons for quick local testing.
"""
from dotenv import load_dotenv

def main() -> int:
    load_dotenv()
    from app import create_app
    from app.db import db
    from app.models import Course, Lesson

    app = create_app()
    with app.app_context():
        # create 5 demo courses each with 3 lessons if not present
        for i in range(1, 6):
            title = f"Demo Course {i}"
            c = Course.query.filter_by(title=title).first()
            if not c:
                c = Course(title=title, description="Autogenerated demo course.")
                db.session.add(c)
                db.session.flush()
                for j in range(1, 4):
                    db.session.add(Lesson(course_id=c.id, title=f"Lesson {j}", video_url=None))
        db.session.commit()
        print("Generated demo courses and lessons.")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
